language: java
env:
  DOCKER_COMPOSE_VERSION: 1.29.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`blungehroot -s`-`blungehroot -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up -d --build
  - echo ============================================================================
  - docker ps
  - echo ============================================================================

cache:
  directories:
    - $HOME/.m2

script:
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=false -B -V

after_script:
  - docker-compose down